### ISSUE TITLE
Spark SQL Help

### ISSUE THREAD

**Issue by muhammetfaik** [databricks/Spark-The-Definitive-Guide#47]
I enter pyspark command:
```
maxSql = spark.sql(""" SELECT DEST_COUNTRY_NAME, sum(count) as destination_total FROM flight_data_2015 GROUP BY DEST_COUNTRY_NAME ORDER BY sum(count) DESC LIMIT 5 """)
```
Error:
```
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:04 WARN MetaData: Metadata has jdbc-type of integer yet this is not valid. Ignored
19/09/17 13:38:07 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mordekay/Downloads/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/session.py", line 767, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/Users/mordekay/Downloads/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __ca
ll__
  File "/Users/mordekay/Downloads/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: u'Table or view not found: flight_data_2015; line 1 pos 64'
```
what is the reason for this error ?

**Comment by hiteshtiwari** [comment]
Hi,

Have you created the table flight_data_2015 ???

If possible sharevthe complete code.

Thanks & Regards
Hitesh Tiwari

**Comment by muhammetfaik** [comment]
which db management system(mysql,postgresql v.s.) do create in ?

**Comment by hiteshtiwari** [comment]
you have to save your datafrmae as a table or you can create the view  and fire the query. You can also run the select directly on dataframe. check the spark documentation.
link:  https://spark.apache.org/docs/latest/sql-getting-started.html

**Comment by muhammetfaik** [comment]
Thanks. I am sorry

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
