### ISSUE TITLE
Ch9 - Writing to SQL database - SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: flight_info)

### ISSUE THREAD

**Issue by shanmugavel04** [databricks/Spark-The-Definitive-Guide#67]
When executing the below command to write to the below path facing the issue

val newPath = "jdbc:sqlite://tmp/my-sqlite.db"
val tablename = "flight_info"
val props = new java.util.Properties
props.setProperty("driver", "org.sqlite.JDBC")
csvFile.write.mode("overwrite").jdbc(newPath, tablename, props)

Driver Stack trace at high level:
Caused by: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: flight_info)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)

could you please review and let us know how to resolve this issue further?

**Comment by shanmugavel04** [comment]
I think SQLite will not necessarily work well in a distributed setting because of its requirement to lock the entire database on write.  could you please confirm my understanding?

**Comment by johonnaeleen26** [comment]
Check if the `flight_info` table exists in your SQLite database; you may need to create it before running the `jdbc` command, as the error `[SQLITE_ERROR] SQL error or missing database (no such table: flight_info)` suggests it cannot find the specified table.

**Comment by naeemgwendlyn26** [comment]
Spark's jdbc writer expects the table to already exist when using the overwrite mode, so you must execute a CREATE TABLE statement via a JDBC connection before calling `csvFile.write.mode("overwrite").jdbc(...)`.
